services:
  control-node:
    build:
      context: control-node
    networks:
      ansible:
        aliases:
          - control_node
    volumes:
      - type: bind
        source: ./source/examples
        target: /home/ansible/tutorial

  managed-node-01:
    build:
      context: managed-node-01
    ports:
      - 22
    networks:
      ansible:
        aliases:
          - managed_node_01

  managed-node-02:
    build:
      context: managed-node-02
    ports:
      - 22
    networks:
      ansible:
        aliases: !override
          - managed_node_02

  managed-node-03:
    build:
      context: managed-node-03
    ports:
      - 22
    networks:
      ansible:
        aliases: !override
          - managed_node_03

  managed-node-04:
    build:
      context: managed-node-04
    ports:
      - 22
    networks:
      ansible:
        aliases: !override
          - managed_node_04

  k3s:
    image: rancher/k3s:v1.30.14-rc1-k3s2
    privileged: true
    command: server
    ports:
      - 6443
    networks:
      ansible:

networks:
  ansible:
