services:
  control-node:
    build:
      context: control-node
    networks:
      ansible:
        aliases:
          - control_node
    volumes:
      - type: bind
        source: ./source/examples
        target: /home/ansible/tutorial

  managed-node-01:
    build:
      context: managed-node
    ports:
      - 22
    networks:
      ansible:
        aliases:
          - managed_node_01

  managed-node-02:
    extends:
      service: managed-node-01
    networks:
      ansible:
        aliases: !override
          - managed_node_02

  managed-node-03:
    extends:
      service: managed-node-01
    networks:
      ansible:
        aliases: !override
          - managed_node_03

networks:
  ansible:
