services:
  control-node:
    build:
      context: control-node
    networks:
      ansible:
        aliases:
          - control_node
    volumes:
      - type: bind
        source: ./source/examples
        target: /home/ansible/tutorial

  managed-node:
    build:
      context: managed-node
    ports:
      - 22
    networks:
      ansible:
        aliases:
          - managed_node

networks:
  ansible:
