[workspace]
authors = ["Raniere Silva <raniere@rgaiacs.com>"]
channels = ["conda-forge"]
name = "rse-ansible-tutorial"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
zip-examples = { cmd = [
    "./zip-examples.sh",
] }
zip-sandbox-docker = { cmd = [
    "zip",
    "-r",
    "source/sandbox-docker.zip",
    "compose.yml",
    "control-node",
    "managed-node-01",
    "managed-node-02",
    "managed-node-03",
    "managed-node-04",
] }

[dependencies]
sphinx = ">=8.2.3,<9"
sphinx-rtd-theme = ">=3.0.1,<4"
sphinx-copybutton = ">=0.5.2,<0.6"
sphinxcontrib-mermaid = ">=1.0.0,<2"
make = ">=4.4.1,<5"
zip = ">=3.0,<4"

[feature.autobuild.dependencies]
sphinx-autobuild = ">=2024.10.3,<2025"

[feature.autobuild.tasks]
preview = { cmd = [
    "sphinx-autobuild",
    "--host",
    "0.0.0.0",
    "./source",
    "./build"
], depends-on = ["zip-examples", "zip-sandbox-docker"] }

[environments]
docs = ["autobuild"]
