apiVersion: v1
kind: Pod
metadata:
  name: rse-ansible-tutorial
spec:
  containers:
    - name: control-node
      image: ghcr.io/rgaiacs/rse-ansible-tutorial/managed-node-01:1.0.0
    - name: managed-node-01
      image: ghcr.io/rgaiacs/rse-ansible-tutorial/managed-node-01:1.0.0
    - name: managed-node-02
      image: ghcr.io/rgaiacs/rse-ansible-tutorial/managed-node-02:1.0.0
    - name: managed-node-03
      image: ghcr.io/rgaiacs/rse-ansible-tutorial/managed-node-03:1.0.0
    - name: managed-node-04
      image: ghcr.io/rgaiacs/rse-ansible-tutorial/managed-node-04:1.0.0
    - name: k3s
      image: rancher/k3s:v1.30.14-rc1-k3s2
