- name: Creating files
  hosts:
    - web
  tasks:
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /tmp/example
        state: directory
        owner: ansible
        group: ansible
        mode: 'u=rwx,g=rx,o=rx'
    - name: Ensure line is present in file
      ansible.builtin.lineinfile:
        path: /tmp/example/answer.txt
        line: '42'
        state: present
        create: true
        owner: ansible
        group: ansible
        mode: 'u=rw,g=r,o=r'
